### ISSUE TITLE
Error python3 run webdev

### ISSUE THREAD

**Issue by SpiderChat** [sanderfoobar/ircradio#6]
python3 run webdev <--- 

Error:

> Traceback (most recent call last):
  File "/home/radio/ircradio/run.py", line 12, in <module>
    from ircradio.factory import create_app
  File "/home/radio/ircradio/ircradio/__init__.py", line 1, in <module>
    from ircradio.utils import liquidsoap_check_symlink
  File "/home/radio/ircradio/ircradio/utils.py", line 16, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

>

**Comment by SpiderChat** [comment]
File "/home/radio/ircradio/venv/lib/python3.10/site-packages/hypercorn/asyncio/lifespan.py", line 101, in asgi_send
    raise LifespanFailureError("startup", message["message"])
hypercorn.utils.LifespanFailureError: Lifespan failure in startup. 'liquidsoap is not running, please start it first'
(venv) radio@radio:~/ircradio$

but in root
root@radio:~# service liquidsoap status
* liquidsoap.service - liquidsoap service
     Loaded: loaded (/etc/systemd/system/liquidsoap.service; enabled; vendor pr>
     Active: active (running) since Sun 2023-04-09 08:46:27 UTC; 1s ago
   Main PID: 25562 (liquidsoap)
      Tasks: 1 (limit: 115901)
     Memory: 69.8M
        CPU: 1.779s
     CGroup: /system.slice/liquidsoap.service
             `-25562 /usr/bin/liquidsoap /home/radio/ircradio/data/soap.liq

Apr 09 08:46:27 radio systemd[1]: Started liquidsoap service.
